[package]
name = "u2f-hid"
version = "0.1.0"
authors = ["Andrii Dmytrenko <refresh.xss@gmail.com>"]

[dependencies]
hid = "*"
byteorder = "*"
error-chain = "*"
rust-crypto = "*"
log = "*"
# enum_primitive = "*"
